services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      SERVER_NAME: "xintero"
      DIFFICULTY: "peaceful"
      ALLOW_NETHER: "TRUE"
      GENERATE_STRUCTURES: "TRUE"
      SPAWN_ANIMALS: "TRUE"
      SPAWN_NPCS: "TRUE"
      MODE: "creative"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - minecraft-data:/data

volumes: 
  minecraft-data:
    external: true