services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      - ALLOW_FLIGHT=1
      - ALLOW_NETHER=1
      - DIFFICULTY=easy
      - DIFFICULTY=peaceful
      - EULA=1
      - GENERATE_STRUCTURES=1
      - MODE=creative
      - SERVER_NAME=xintero
      - SPAWN_ANIMALS=1
      - SPAWN_NPCS=1
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - minecraft-data:/data

volumes: 
  minecraft-data:
    external: true